const express=require('express');const http=require('http');const {Server}=require('socket.io');const fs=require('fs');const path=require('path');const helmet=require('helmet');const cors=require('cors');const rateLimit=require('express-rate-limit');
const app=express();const server=http.createServer(app);const io=new Server(server,{cors:{origin:"*"},maxHttpBufferSize:2e6});
const PORT=process.env.PORT||10000;const DATA=path.join(__dirname,'data');const PUB=path.join(__dirname,'public');if(!fs.existsSync(DATA))fs.mkdirSync(DATA,{recursive:true});
const PO=path.join(DATA,'posts.json'),WA=path.join(DATA,'wallet.json'),US=path.join(DATA,'users.json');
const load=(f,d)=>{try{return fs.existsSync(f)?JSON.parse(fs.readFileSync(f,'utf8')):d}catch{return d}};const save=(f,d)=>{try{fs.writeFileSync(f,JSON.stringify(d,null,2))}catch(e){}};
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#x27;'}[c])).slice(0,800);
let posts=load(PO,[]),wallets=load(WA,{'AL':{balance:1000,earned:0}}),users=load(US,{}),liveAudience=0,liveUsers=new Map();
app.use(helmet({contentSecurityPolicy:false}));app.use(cors({origin:"*"}));app.use(express.json({limit:"10mb"}));app.use(express.static(PUB));app.use('/api/',rateLimit({windowMs:60000,max:120}));
app.get('/api/posts',(req,res)=>res.json(posts.slice(-100).reverse()));
app.post('/api/posts',(req,res)=>{const b=req.body;if(!b.text&&!b.media)return res.json({error:'فارغ'});if(b.media&&b.media.length>700000)b.media=b.media.slice(0,700000);const p={id:Date.now(),user:esc(b.user||'AL').slice(0,20),text:esc(b.text).slice(0,500),media:b.media||'',type:esc(b.type||'text'),likes:0,time:Date.now(),audience:liveAudience};posts.push(p);if(posts.length>500)posts.shift();save(PO,posts);io.emit('broadcast_post',p);res.json({ok:true})});
app.get('/api/wallet/:user',(req,res)=>{const u=esc(req.params.user).toUpperCase().slice(0,20);if(!wallets[u]){wallets[u]={balance:500,earned:0};save(WA,wallets);}res.json(wallets[u])});
app.post('/api/wallet/gift',(req,res)=>{let {from,to,gift}=req.body;from=esc(from).toUpperCase().slice(0,20);to=esc(to||'AL').toUpperCase().slice(0,20);const prices={'🎁':10,'❤️':5,'👑':50,'🚀':100};const price=prices[gift]||10;if(!wallets[from])wallets[from]={balance:500,earned:0};if(!wallets[to])wallets[to]={balance:1000,earned:0};if(wallets[from].balance<price)return res.json({error:'رصيدك لا يكفي'});wallets[from].balance-=price;wallets[to].balance+=Math.floor(price*0.7);wallets[to].earned+=Math.floor(price*0.7);save(WA,wallets);io.emit('gift_received',{from,gift,price,liveAudience});res.json({yourBalance:wallets[from].balance})});
app.get('/api/audience',(req,res)=>res.json({count:liveAudience,users:Array.from(liveUsers.values())}));
app.post('/api/upload',(req,res)=>res.json({url:req.body.videoBase64||''}));
app.post('/api/support',(req,res)=>res.json({reply:'🛡️ تم استلام: "'+esc(req.body.text).slice(0,100)+'" - slmanmktbabw@gmail.com'}));
app.post('/api/register',(req,res)=>{const u=esc(req.body.user).toUpperCase().slice(0,20)||'AL';users[u]={last:Date.now()};save(US,users);if(!wallets[u]){wallets[u]={balance:1000,earned:0};save(WA,wallets);}res.json({ok:true,user:u})});
io.on('connection',socket=>{
  liveAudience++;socket.on('join_live',d=>{const u=esc(d.user).slice(0,20)||'ANON';liveUsers.set(socket.id,u);io.emit('update_audience',{count:liveAudience,users:Array.from(liveUsers.values()),joined:u});});
  socket.on('disconnect',()=>{liveAudience=Math.max(0,liveAudience-1);const u=liveUsers.get(socket.id);liveUsers.delete(socket.id);io.emit('update_audience',{count:liveAudience,users:Array.from(liveUsers.values()),left:u});});
  socket.on('new_post',p=>socket.broadcast.emit('broadcast_post',p));socket.on('live_like',d=>io.emit('live_like',d));socket.on('live_comment',d=>io.emit('live_comment',{user:esc(d.user),text:esc(d.text)}));socket.on('private_message',d=>io.emit('private_message',{user:esc(d.user),text:esc(d.text)}));
});
app.get('*',(req,res)=>res.sendFile(path.join(PUB,'index.html')));
server.listen(PORT,()=>console.log('🏰 TARIM OS V11.1 REAL AUDIENCE on '+PORT));
